name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04-arm, macos-26, macos-26-intel]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run tests on Linux (gcc)
        if: runner.os == 'Linux'
        run: make test

      - name: Run tests on Linux (clang)
        if: runner.os == 'Linux'
        run: CC=clang make test

      - name: Install GNU tools on macOS
        if: runner.os == 'macOS'
        run: brew install make

      - name: Run tests on macOS (gcc)
        if: runner.os == 'macOS'
        run: CC=gcc-15 gmake test

      - name: Run tests on macOS (clang)
        if: runner.os == 'macOS'
        run: gmake test

